name: dartmcp
description: A starting point for Dart libraries or applications.
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  dart_mcp: ^0.1.0

dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.15
